nodeLinker: node-modules

# We need to run postinstall always otherwise patching will not be applied sometimes
# More about behavior here https://github.com/GravitywellUK/yarn-plugin-postinstall
postinstall: yarn run postinstall-legacy

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall.cjs
    spec: "https://raw.githubusercontent.com/gravitywelluk/yarn-plugin-postinstall/master/bundles/%40yarnpkg/plugin-postinstall.js"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
